---
- name: OpenMeetings | install requirement
  apt:
    pkg={{ item }}
    state=latest
  with_items:
    - "autoconf"
    - "automake"
    - "build-essential"
    - "libass-dev"
    - "libfreetype6-dev"
    - "libsdl1.2-dev"
    - "libtheora-dev"
    - "libtool libva-dev"
    - "libvdpau-dev"
    - "libvorbis-dev"
    - "libxcb1-dev"
    - "libxcb-shm0-dev"
    - "libxcb-xfixes0-dev"
    - "pkg-config"
    - "texi2html"
    - "zlib1g-dev"
    - "mercurial"
    - "cmake"