---
- name: build sox | uninstall sox package
  apt:
    pkg={{ item }}
    state=absent
  with_items:
    - sox

- name: build sox | install requirement
  apt:
    pkg={{ item }}
    state=latest
  with_items:
    - "libflac-dev"
    - "libogg-dev"
    - "libvorbis-dev"
    - "libmp3lame-dev"
    - "libid3tag0-dev"
    - "libtwolame-dev"
    - "libopus-dev"
    - "libopusfile-dev"
    - "libsndfile1-dev"
    - "libasound2-dev"
    - "libpulse-dev"
    - "libwavpack-dev"
    - "libmad0-dev"
    - "libopencore-amrnb-dev"
    - "libopencore-amrwb-dev"
    - "libmagic-dev"
    - "libao-dev"

- name: build sox | check {{ glx_sox_source_dir }} directory
  file:
    path="{{ glx_sox_source_dir }}"
    state=directory

- name: build sox | delete "{{ glx_sox_source_dir }}/{{ glx_sox_app_name }}.{{ glx_sox_extension }}"
  file:
    path="{{ glx_sox_source_dir }}/{{ glx_sox_app_name }}.{{ glx_sox_extension }}"
    state=absent
  when: glx_sox_force_install

- name: build sox | get "{{ glx_sox_download_url }}"
  get_url:
    url="{{ glx_sox_download_url }}"
    dest="{{ glx_sox_source_dir }}"
    sha256sum="{{ glx_sox_sha256sum }}"
  register: glx_sox_source_download

- name: build sox | delete "{{ glx_sox_source_dir }}/{{ glx_sox_app_name }}" directory
  file:
    path="{{ glx_sox_source_dir }}/{{ glx_sox_app_name }}"
    state=absent
  when: glx_sox_source_download.changed

- name: build sox | unarchive {{ glx_sox_source_download.dest }}
  unarchive:
    src="{{ glx_sox_source_download.dest }}"
    dest="{{ glx_sox_source_dir }}"
    copy=no
  when: glx_sox_source_download.changed

- name: run configure script ...
  shell: ./configure \
          --prefix={{ glx_sox_prefix }} \
          --sysconfdir={{ glx_sox_sysconfdir }} \
          --enable-dl-mad \
          --enable-dl-lame \
          --enable-dl-twolame \
          --enable-dl-amrwb \
          --enable-dl-amrnb \
          --enable-dl-sndfile
    chdir="{{ glx_sox_source_dir }}/{{ glx_sox_app_name }}"
  changed_when: false

- name: make -s
  shell: make -s
    chdir="{{ glx_sox_source_dir }}/{{ glx_sox_app_name }}"
  changed_when: false

- name: make install
  shell: make install
    chdir="{{ glx_sox_source_dir }}/{{ glx_sox_app_name }}"
  changed_when: false