---
# Clean Debian packages
- name: build opus | unnstall doublon
  apt:
    pkg={{ item }}
    state=absent
  with_items:
    - "libopus0"
    - "libopus-dev"
    - "libopusfile0"
    - "libopusfile-dev"

# Download opus sources
- name: build opus | clone latest opus
  git:
    repo=git://git.opus-codec.org/opus.git
    dest={{ glx_ffmpeg_source_dir }}/opus
    accept_hostkey=yes

# Build opus
- name: build opus | compile libopus
  command: "{{ item }}"
  args:
    chdir: "{{ glx_ffmpeg_source_dir }}/opus"
    creates: "{{ glx_ffmpeg_lib_dir }}/libopus.a"
  with_items:
    - ./autogen.sh
    - ./configure --prefix={{ glx_ffmpeg_prefix }} --disable-shared
    - make
    - make install
    - make distclean
