---
- name: OpenMeetings | install requirement
  apt:
    pkg={{ item }}
    state=latest
  with_items:
    - "autoconf"
    - "automake"
    - "libass-dev"
    - "libfreetype6-dev"
    - "libgpac-dev"
    - "libsdl1.2-dev"
    - "libtheora-dev"
    - "libtool"
    - "libva-dev"
    - "libvdpau-dev"
    - "libvorbis-dev"
    - "libxcb1-dev"
    - "libxcb-shm0-dev"
    - "libxcb-xfixes0-dev"
    - "pkg-config"
    - "texi2html"
    - "zlib1g-dev"
    - "nasm"
    - "libx264-dev"
    - "cmake"
    - "mercurial"
    - "libopus-dev"

- name: build ffmpeg | check {{ glx_ffmpeg_source_dir }} directory
  file:
    path="{{ glx_ffmpeg_source_dir }}"
    state=directory