---
- name: apache2 | install Apache
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2
    - apache2-utils
    - apache2-mpm-prefork
    - libapache2-mod-fcgid
    - libcgi-fast-perl
  notify:
    - service apache2 restart

# Disable server Signature and Version thing
# http://ask.xmodulo.com/turn-off-server-signature-apache-web-server.html

- name: apache2 | check "ServerSignature Off" to "{{ glx_apache_sysconfdir }}/apache2/apache2.conf"
  lineinfile:
    dest="{{ glx_apache_sysconfdir }}/apache2/apache2.conf"
    state=present
    regexp='^# ServerSignature *|^#ServerSignature *|^ServerSignature *'
    line='ServerSignature Off'
    insertbefore="^# vim*"
  notify:
    - service apache2 restart

- name: apache2 | check "ServerTokens Prod" to "{{ glx_apache_sysconfdir }}/apache2/apache2.conf"
  lineinfile:
    dest="{{ glx_apache_sysconfdir }}/apache2/apache2.conf"
    regexp='^\# ServerTokens *|^\#ServerTokens *|^ServerTokens *'
    line="ServerTokens Prod"
    insertbefore="^# vim*"
    state=present
  notify:
    - service apache2 restart

- name: apache2 | add "{{ galaxie_ansible_user }}" user in www-data group
  user:
    name: "{{ galaxie_ansible_user }}"
    groups: "www-data"
    append: yes

- name: apache2 | enable the fcgid module in apache
  apache2_module:
    state=present
    name="fcgid"
  notify:
    - service apache2 restart

- name: apache2 | enable the auth_digest module in apache
  apache2_module:
    state=present
    name="auth_digest"
  notify:
    - service apache2 restart

- name: apache2 | enable the ssl module in apache
  apache2_module:
    state=present
    name="ssl"
  notify:
    - service apache2 restart

- name: apache2 | enable the rewrite module in apache
  apache2_module:
    state=present
    name="rewrite"
  notify:
    - service apache2 restart

### HTTP
- name: apache2 | creat HTTP virtual hosts files
  template:
    src="000-default.conf.j2"
    dest="{{ glx_apache_sysconfdir }}/apache2/sites-available/{{ item.ServerName }}.conf"
    owner="root"
    group="root"
    mode=0644
  with_items: glx_apache_virtualhosts

- name: apache2 | creat DocumentRoot dor for each HTTP Virtual hosts
  file:
    path="{{ item.DocumentRoot }}"
    state=directory
    owner="www-data"
    group="www-data"
    mode=2775
  with_items: glx_apache_virtualhosts

- name: apache2 | blanck page if need
  copy:
    src=index.php
    dest={{ item.DocumentRoot }}/index.php
    force=no
    owner="www-data"
    group="www-data"
    mode=0664
  with_items: glx_apache_virtualhosts

- name: apache2 | a2ensite virtual hosts
  command: a2ensite {{ item.ServerName }}
    creates="{{ glx_apache_sysconfdir }}/apache2/sites-enabled/{{ item.ServerName }}.conf"
  with_items: glx_apache_virtualhosts
  notify:
    - service apache2 restart

### HTTPS
- name: apache2 | creat HTTPS virtual hosts files
  template:
    src="default-ssl.conf.j2"
    dest="{{ glx_apache_sysconfdir }}/apache2/sites-available/{{ item.ServerName }}-ssl.conf"
    owner="root"
    group="root"
    mode=0644
  with_items: glx_apache_ssl_virtualhosts

- name: apache2 | creat DocumentRoot dor for each HTTPS Virtual hosts
  file:
    path="{{ item.DocumentRoot }}"
    state=directory
    owner="www-data"
    group="www-data"
    mode=2775
  with_items: glx_apache_ssl_virtualhosts

- name: apache2 | blanck page if need
  copy:
    src=index.php
    dest={{ item.DocumentRoot }}/index.php
    force=no
    owner="www-data"
    group="www-data"
    mode=0664
  with_items: glx_apache_ssl_virtualhosts

#- name: apache2 | a2ensite SSL virtual hosts
#  command: a2ensite {{ item.ServerName }}-ssl
#    creates="{{ glx_apache_sysconfdir }}/apache2/sites-enabled/{{ item.ServerName }}-ssl.conf"
#  with_items: glx_apache_ssl_virtualhosts
#  notify:
#    - service apache2 restart
