---
# [inspired_by] https://wiki.debian.org/WordPress#An_alternate_installation_method

- name: create wordpress configuration file peer ServerName
  template:
    src="wordpress_configuration_file.j2"
    dest="{{ glx_wordpress_sysconfdir }}/wordpress/config-{{ item.ServerName }}.php"
    owner="root"
    group="{{ glx_apache_gname }}"
    mode=0640
  with_items: glx_apache_virtualhosts
  notify:
    - service apache2 restart

# [inspired_by] /usr/share/doc/wordpress/README.Debian
# Permit to update actual default skin
- name: check if {{ glx_wordpress_content_dir }}/themes/twentyfifteen is a symlink
  stat:
    path="{{ glx_wordpress_content_dir }}/themes/twentyfifteen"
  register: twentyfifteen_dir

#- debug: msg="{{ twentyfifteen_dir }}"

- name: remove {{ glx_wordpress_content_dir }}/themes/twentyfifteen (only if it is a link)
  file:
    path="{{ glx_wordpress_content_dir }}/themes/twentyfifteen"
    state=absent
  register: twentyfifteen_link
  when: twentyfifteen_dir.stat.islnk is defined and twentyfifteen_dir.stat.islnk

- name: copy {{ glx_wordpress_root_dir }}/wp-content/themes/twentyfifteen to {{ glx_wordpress_content_dir }}/themes/
  shell: cp -R {{ glx_wordpress_root_dir }}/wp-content/themes/twentyfifteen {{ glx_wordpress_content_dir }}/themes/
    chdir="{{ glx_wordpress_content_dir }}"
  when: twentyfifteen_link|changed

# [inspired_by] /usr/share/doc/wordpress/README.Debian
# Permit to update plugins akismet
- name: check if {{ glx_wordpress_content_dir }}/plugins/akismet is a symlink
  stat:
    path="{{ glx_wordpress_content_dir }}/plugins/akismet"
  register: akismet_dir

#- debug: msg="{{ akismet_dir }}"

- name: remove {{ glx_wordpress_content_dir }}/plugins/akismet (only if it is a link)
  file:
    path="{{ glx_wordpress_content_dir }}/plugins/akismet"
    state=absent
  register: akismet_link
  when: akismet_dir.stat.islnk is defined and akismet_dir.stat.islnk

- name: copy {{ glx_wordpress_root_dir }}/wp-content/plugins/akismet to {{ glx_wordpress_content_dir }}/plugins/
  shell: cp -R {{ glx_wordpress_root_dir }}/wp-content/plugins/akismet {{ glx_wordpress_content_dir }}/plugins/
    chdir="{{ glx_wordpress_content_dir }}"
  when: akismet_link|changed

# [inspired_by] /usr/share/doc/wordpress/README.Debian
# index.php is editable
- name: check if {{ glx_wordpress_content_dir }}/plugins/index.php is a symlink
  stat:
    path="{{ glx_wordpress_content_dir }}/plugins/index.php"
  register: index_php_file

#- debug: msg="{{ index_php_file }}"

- name: remove {{ glx_wordpress_content_dir }}/plugins/index.php (only if it is a link)
  file:
    path="{{ glx_wordpress_content_dir }}/plugins/index.php"
    state=absent
  register: index_php_link
  when: index_php_file.stat.islnk is defined and index_php_file.stat.islnk

- name: copy {{ glx_wordpress_root_dir }}/wp-content/plugins/index.php to {{ glx_wordpress_content_dir }}/plugins/index.php
  shell: cp {{ glx_wordpress_root_dir }}/wp-content/plugins/index.php {{ glx_wordpress_content_dir }}/plugins/index.php
    chdir="{{ glx_wordpress_content_dir }}"
  when: index_php_link|changed

# [inspired_by] /usr/share/doc/wordpress/README.Debian
# Permit language update
- name: check if {{ glx_wordpress_content_dir }}/languages/admin-fr_FR.mo is a symlink
  stat:
    path="{{ glx_wordpress_content_dir }}/languages/admin-fr_FR.mo"
  register: languages_checked_file

#- debug: msg="{{ languages_checked_file }}"

- name: remove {{ glx_wordpress_content_dir }}/languages (only if contain links)
  file:
    path="{{ glx_wordpress_content_dir }}/languages"
    state=absent
  register: languages_checked_file_link
  when: languages_checked_file.stat.islnk is defined and languages_checked_file.stat.islnk

- name: copy {{ glx_wordpress_root_dir }}/wp-content/languages to {{ glx_wordpress_content_dir }}/languages
  shell: cp -R {{ glx_wordpress_root_dir }}/wp-content/languages {{ glx_wordpress_content_dir }}/
    chdir="{{ glx_wordpress_content_dir }}"
  when: languages_checked_file_link|changed

# Check permission
- name: wordpress will able to edit themes and to update plugins
  shell: chown -R {{ glx_apache_uname }}:{{ glx_apache_gname }} {{ glx_wordpress_content_dir }}
    chdir="{{ glx_wordpress_content_dir }}"
  changed_when: false

- name: wordpress set permission
  file:
    path="{{ glx_wordpress_content_dir }}/{{ item }}"
    mode="2775"
    owner="{{ glx_apache_uname }}"
    group="{{ glx_apache_gname }}"
    state=directory
  with_items:
    - "blogs.dir"
    - "languages"
    - "plugins"
    - "themes"
    - "upgrade"
    - "uploads"
  changed_when: false

- name: wordpress chanche owner of subdir in {{ glx_wordpress_content_dir }}/
  shell: chown -R {{ glx_apache_uname }}:{{ glx_apache_gname }} {{ glx_wordpress_content_dir }}/{{ item }}
    chdir="{{ glx_wordpress_content_dir }}"
  with_items:
    - "blogs.dir"
    - "languages"
    - "plugins"
    - "themes"
    - "upgrade"
    - "uploads"
  changed_when: false

- name: wordpress remove write permission to others of subdir in {{ glx_wordpress_content_dir }}/
  shell: chmod -R o-w {{ glx_wordpress_content_dir }}/{{ item }}
    chdir="{{ glx_wordpress_content_dir }}"
  with_items:
    - "blogs.dir"
    - "languages"
    - "plugins"
    - "themes"
    - "upgrade"
    - "uploads"
  changed_when: false

- name: wordpress set files to 664 and directory to 775
  shell: chmod -R u+rwX,g+rwX,o+rX {{ glx_wordpress_content_dir }}/{{ item }}
    chdir="{{ glx_wordpress_content_dir }}"
  with_items:
    - "blogs.dir"
    - "languages"
    - "plugins"
    - "themes"
    - "upgrade"
    - "uploads"
  changed_when: false
