---
# Disable server Signature and Version thing
# [inspired_by] http://ask.xmodulo.com/turn-off-server-signature-apache-web-server.html
- name: apache2 | check "ServerSignature Off" to "{{ glx_apache_sysconfdir }}/apache2/apache2.conf"
  lineinfile:
    dest="{{ glx_apache_sysconfdir }}/apache2/apache2.conf"
    state=present
    regexp='^# ServerSignature *|^#ServerSignature *|^ServerSignature *'
    line='ServerSignature Off'
    insertbefore="^# vim*"
  notify:
    - service apache2 restart

# Disable server Signature and Version thing
# [inspired_by] http://ask.xmodulo.com/turn-off-server-signature-apache-web-server.html
- name: apache2 | check "ServerTokens Prod" to "{{ glx_apache_sysconfdir }}/apache2/apache2.conf"
  lineinfile:
    dest="{{ glx_apache_sysconfdir }}/apache2/apache2.conf"
    regexp='^\# ServerTokens *|^\#ServerTokens *|^ServerTokens *'
    line="ServerTokens Prod"
    insertbefore="^# vim*"
    state=present
  notify:
    - service apache2 restart

- name: apache2 | enable the fcgid module in apache
  apache2_module:
    state=present
    name="fcgid"
  notify:
    - service apache2 restart

- name: apache2 | enable the auth_digest module in apache
  apache2_module:
    state=present
    name="auth_digest"
  notify:
    - service apache2 restart

- name: apache2 | enable the ssl module in apache
  apache2_module:
    state=present
    name="ssl"
  notify:
    - service apache2 restart

- name: apache2 | enable the rewrite module in apache
  apache2_module:
    state=present
    name="rewrite"
  notify:
    - service apache2 restart

# Start apache in case
- name: service apache2 start
  service:
    name=apache2
    state=started
    enabled=yes
