---
# [inspired_by] https://wiki.debian.org/WordPress#An_alternate_installation_method

- name: General | Install required packages.
  apt:
   pkg={{ item }}
   state=installed
  with_items:
    - wordpress
    - wordpress-l10n
    - unzip
    - tar
    - gzip
    - bzip2
