---
- name: php5 | Check php5 installation
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-cli
    - php5-mysql
    - libapache2-mod-php5
    - php5
    - php5-apcu
    - php5-common
    - php5-curl
    - php5-dev
    - php5-gd
    - php5-intl
    - php-pear
    - php5-imap
    - php5-json
    - php5-mcrypt
    - php5-memcache
    - php5-mysql
    - php5-pspell
    - php5-recode
    - php5-tidy
    - php5-xmlrpc
    - php5-xsl
    - php-xml-rss
    - php5-sqlite
  notify:
    - service apache2 restart
