---
#- include: self-signed-cert.yml
#  when: glx_apache_use_self_signed_certs

- include: apache.yml
  when: install_apache

- include: php.yml
  when: install_php

#- include: wordpress.yml
#  when: install_wordpress
