---
### Users and Webmasters write authorizations
- name: apache2 | add {{ glx_apache_webmasters }} to {{ glx_apache_gname }} group
  user:
    name="{{ item }}"
    groups="{{ glx_apache_gname }}"
    append=yes
  with_items: glx_apache_webmasters
  tags: config, config-webmasters

### CERTIFICATES
- include: self-signed-cert.yml
  tags: config-self-signed-cert

- include: self-signed-cert.yml
  tags: config-valid-cert

### APACHE
- include: install-apache.yml
  tags: install, install-apache
  when: install_apache

- include: config-apache.yml
  tags: config, config-apache
  when: install_apache

- include: config-apache-virtualhosts.yml
  tags: config, config-apache-virtualhosts
  when: install_apache

### MYSQL
- include: config-mysql.yml
  tags: config, config-mysql

### PHP
- include: install-php.yml
  tags: install, install-php
  when: install_php

- include: config-php.yml
  tags: config, config-php
  when: install_php

### WORDPRESS
- include: install-wordpress.yml
  when: install_wordpress

- include: config-wordpress.yml
  tags: config, config-wordpress
  when: install_wordpress