---
### Users and Webmasters write authorizations
- name: apache2 | add {{ glx_apache_webmasters }} to {{ glx_apache_gname }} group
  user:
    name="{{ item }}"
    groups="{{ glx_apache_gname }}"
    append=yes
  with_items: glx_apache_webmasters
  tags: config, config-webmasters

### CERTIFICATES
- include: config-certificats.yml
  tags: config, config-certificats

### APACHE
- include: install-apache.yml
  tags: install, install-apache
  when: install_apache

- include: config-apache.yml
  tags: config, config-apache
  when: install_apache

- include: config-apache-virtualhosts.yml
  tags: config, config-apache-virtualhosts
  when: install_apache

### MYSQL
- include: config-mysql.yml
  when: "{{ 'mysql-servers' in group_names }}"
  tags: config, config-mysql

### PHP
#- include: install-php.yml
#  tags: install, install-php
#  when: install_php and ansible_distribution == "Debian" and ansible_distribution_major_version == "8"
#
#- include: config-php.yml
#  tags: config, config-php
#  when: install_php and ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

### WORDPRESS
- include: install-wordpress.yml
  when: "{{ 'wordpress' in group_names }}"

- include: config-wordpress-ssl.yml
  tags: config, config-wordpress-ssl
  when: "{{ 'wordpress' in group_names }}"
