---
- name: apache2 | creat certificats directory's
  file:
    path="{{ item }}"
    state=directory
    owner="root"
    group="ssl-cert"
    mode=0710
  with_items:
    - "{{ glx_apache_localcerts_dir }}"
    - "{{ glx_apache_privacerts_dir }}"

- name: apache2 | delete previous certificates .pem
  file:
    path="{{ glx_apache_localcerts_dir }}/ssl-cert-{{ item.ServerName }}.pem"
    state=absent
  with_items: glx_apache_ssl_virtualhosts
  when: glx_apache_force_self_signed_gen

- name: apache2 | delete previous certificates .key
  file:
    path="{{ glx_apache_localcerts_dir }}/ssl-cert-{{ item.ServerName }}.key"
    state=absent
  with_items: glx_apache_ssl_virtualhosts
  when: glx_apache_force_self_signed_gen

### Generate self signed certificate it match with ServerName
- name: apache2 | generaterate self-signed .pem and .key certificate for each Virtual host
  command: openssl req -new -x509 -days {{ glx_apache_openssl_key_days }} -nodes -out {{ glx_apache_localcerts_dir }}/ssl-cert-{{ item.ServerName }}.pem -keyout {{ glx_apache_localcerts_dir }}/ssl-cert-{{ item.ServerName }}.key -subj "/C={{ glx_apache_openssl_cert_C }}/ST={{ glx_apache_openssl_cert_ST }}/L={{ glx_apache_openssl_cert_L }}/O={{ glx_apache_openssl_cert_O }}/OU={{ glx_apache_openssl_cert_OU }}/CN=*.{{ item.ServerName }}"
    creates="{{ glx_apache_localcerts_dir }}/ssl-cert-{{ item.ServerName }}.pem"
  with_items: glx_apache_ssl_virtualhosts
  notify:
    - service apache2 restart

- name: apache2 | check {{ glx_apache_localcerts_dir }}/ssl-cert-*.pem certificats permission
  file:
    path="{{ glx_apache_localcerts_dir }}/ssl-cert-{{ item.ServerName }}.pem"
    owner="root"
    group="ssl-cert"
    mode=0640
  with_items: glx_apache_ssl_virtualhosts

- name: apache2 | check {{ glx_apache_localcerts_dir }}/ssl-cert-*.key certificats permission
  file:
    path="{{ glx_apache_localcerts_dir }}/ssl-cert-{{ item.ServerName }}.key"
    owner="root"
    group="ssl-cert"
    mode=0640
  with_items: glx_apache_ssl_virtualhosts

### Generate .csr for use a valide signed certificate
- name: apache2 | generaterate .csr and .key for each Virtual host in case of use signed certs
  command: openssl req -nodes -newkey rsa:{{ glx_apache_openssl_key_bit }} -sha512 -keyout {{ glx_apache_privacerts_dir }}/ssl-cert-{{ item.ServerName }}.key -out {{ glx_apache_privacerts_dir }}/ssl-cert-{{ item.ServerName }}.csr -subj "/C={{ glx_apache_openssl_cert_C }}/ST={{ glx_apache_openssl_cert_ST }}/L={{ glx_apache_openssl_cert_L }}/O={{ glx_apache_openssl_cert_O }}/OU={{ glx_apache_openssl_cert_OU }}/CN=*.{{ item.ServerName }}"
    creates="{{ glx_apache_privacerts_dir }}/ssl-cert-{{ item.ServerName }}.csr"
  with_items: glx_apache_ssl_virtualhosts
  notify:
    - service apache2 restart

- name: apache2 | check {{ glx_apache_privacerts_dir }}/ssl-cert-*.pem certificats permission
  file:
    path="{{ glx_apache_privacerts_dir }}/ssl-cert-{{ item.ServerName }}.csr"
    owner="root"
    group="ssl-cert"
    mode=0640
  with_items: glx_apache_ssl_virtualhosts

- name: apache2 | check {{ glx_apache_privacerts_dir }}/ssl-cert-*.key certificats permission
  file:
    path="{{ glx_apache_privacerts_dir }}/ssl-cert-{{ item.ServerName }}.key"
    owner="root"
    group="ssl-cert"
    mode=0640
  with_items: glx_apache_ssl_virtualhosts