---
install_apache: true
install_mysql: false
install_php: true
install_wordpress: false

########################
###      APACHE      ###
########################
# Webmaster who have permission to write via groups www-data
glx_apache_webmasters:
  - "{{ galaxie_ansible_user }}"

# Common Setting
glx_apache_sysconfdir: "/etc"
glx_apache_wwwdir: "/var/www"
glx_apache_uname: "www-data"
glx_apache_gname: "www-data"
gtx_apache_http_port: "80"
gtx_apache_https_port: "443"

# SSL
glx_apache_use_self_signed_certs: true
glx_apache_force_self_signed_gen: true
glx_apache_localcerts_dir: "/etc/ssl/localcerts"

# Virtual Domains list to configure
glx_apache_virtualhosts:
  - { VirtualHost: "*:{{ gtx_apache_http_port }}", ServerName: "galaxie.ici", ServerAlias: ['www'], ServerAdmin: "webmaster@galaxie.ici", DocumentRoot: "{{ glx_apache_wwwdir }}/galaxie.ici" }

glx_apache_ssl_virtualhosts:
  - { VirtualHost: "_default_:{{ gtx_apache_https_port }}", ServerName: "galaxie.ici", ServerAlias: ['www'], ServerAdmin: "webmaster@galaxie.ici", DocumentRoot: "{{ glx_apache_wwwdir }}/galaxie.ici" }

# PHP Setting
glx_apache2_php_ini_file: "/etc/php5/apache2/php.ini"