---
install_apache: true
install_mysql: false
install_php: true
install_wordpress: false

########################
###      APACHE      ###
########################

# Apache sysconfigdir
glx_apache_sysconfdir: "/etc"
glx_apache_wwwdir: "/var/www"


# Virtual Domains list to configure
glx_apache_virtualhosts:
  - { VirtualHost: "*:80", ServerName: "galaxie.ici", ServerAdmin: "webmaster@galaxie.ici", DocumentRoot: "{{ glx_apache_wwwdir }}/galaxie.ici" }

glx_apache_ssl_virtualhosts:
  - { VirtualHost: "_default_:443", ServerName: "galaxie.ici", ServerAdmin: "webmaster@galaxie.ici", DocumentRoot: "{{ glx_apache_wwwdir }}/galaxie.ici" }

# PHP Setting
glx_apache2_php_ini_file: "/etc/php5/apache2/php.ini"