---
install_apache: true
install_mysql: false
install_php: true
install_wordpress: true

########################
###      APACHE      ###
########################
# Webmaster who have permission to write via groups www-data
glx_apache_webmasters:
  - "{{ galaxie_ansible_user }}"

# Common Setting
glx_apache_sysconfdir: "/etc"
glx_apache_wwwdir: "/var/www"
glx_apache_uname: "www-data"
glx_apache_gname: "www-data"
glx_apache_http_port: "80"
glx_apache_https_port: "443"

# SSL
glx_apache_use_self_signed_certs: true
glx_apache_force_self_signed_gen: false
glx_apache_localcerts_dir: "/etc/ssl/localcerts"
glx_apache_privacerts_dir: "/etc/ssl/private"
# certificate
glx_apache_openssl_key_bit: "2048"
glx_apache_openssl_key_days: "365"
glx_apache_openssl_cert_C: ""
glx_apache_openssl_cert_ST: ""
glx_apache_openssl_cert_L: ""
glx_apache_openssl_cert_O: "Galaxie"
glx_apache_openssl_cert_OU: "IT"
#glx_apache_openssl_cert_CN: "{{ ansible_hostname }}.{{ glx_apache_domain }}"
#glx_apache_openssl_subj: "/C={{ glx_apache_openssl_cert_C }}/ST={{ glx_apache_openssl_cert_ST }}/L={{ glx_apache_openssl_cert_L }}/O={{ glx_apache_openssl_cert_O }}/OU={{ glx_apache_openssl_cert_OU }}/CN={{ glx_apache_openssl_cert_CN }}"


# Virtual Domains list to configure
glx_apache_virtualhosts:
  - VirtualHost: "*:{{ glx_apache_http_port }}"
    ServerName: "galaxie.ici"
    ServerAlias:
      - "www"
    ServerAdmin: "webmaster@galaxie.ici"
    DocumentRoot: "{{ glx_apache_wwwdir }}/galaxie.ici"

glx_apache_ssl_virtualhosts:
  - VirtualHost: "_default_:{{ glx_apache_https_port }}"
    ServerName: "galaxie.ici"
    ServerAlias:
      - "www"
    ServerAdmin: "webmaster@galaxie.ici"
    DocumentRoot: "{{ glx_apache_wwwdir }}/galaxie.ici"
    AutoSignedCert: true

# PHP Setting
glx_apache2_php_ini_file: "/etc/php5/apache2/php.ini"

# Wordpress
glx_wordpress_db_name: "{{ lookup('password', '{{ playbook_dir }}/../secrets/{{ ansible_hostname }}.wordpress_{{ item.ServerName }}.db_name length=16 chars=ascii_letters,digits') }}"
glx_wordpress_db_user: "{{ lookup('password', '{{ playbook_dir }}/../secrets/{{ ansible_hostname }}.wordpress_{{ item.ServerName }}.db_user length=16 chars=ascii_letters,digits') }}"
glx_wordpress_db_password: "{{ lookup('password', '{{ playbook_dir }}/../secrets/{{ ansible_hostname }}.wordpress_{{ item.ServerName }}.db_password length=16 chars=ascii_letters,digits') }}"
