---
glx_prefix: "/var/lib/galaxie"
glx_packages_dir: "{{ glx_prefix }}/pkgs"
glx_source_dir: "/usr/src"

glx_opt_dir: "/opt"



# sox
glx_sox_force_install: true
# Original Source
# glx_sox_repository: "http://sourceforge.net/projects/sox/files/sox/14.4.2/"
glx_sox_repository: "https://raw.githubusercontent.com/Tuuux/galaxie/master/roles/openmeetings-server/files"
glx_sox_app_name: "sox-14.4.2"
glx_sox_extension: "tar.gz"
glx_sox_download_url: "{{ glx_sox_repository }}/{{ glx_sox_app_name }}.{{ glx_sox_extension }}"
glx_sox_sha256sum: "b45f598643ffbd8e363ff24d61166ccec4836fea6d3888881b8df53e3bb55f6c"
glx_sox_source_dir: "/usr/src"
glx_sox_prefix: "/usr"
glx_sox_sysconfdir: "/etc"

# ffmpeg
glx_ffmpeg_force_install: true
#
glx_ffmpeg_source_dir: "/usr/src"