---
- name: General | Install required packages.
  tags: debs
  action: apt pkg={{ item }} state=installed
  with_items:
    - php5
    - apache2
    - libapache2-modsecurity
    - mysql-server
    - mysql-client
    - php5-mysql
    - php-apc
    - php5-xmlrpc
    - php-soap
    - php5-gd
    - php5-memcache
    - php5-memcached
    - php5-curl
    - php5-tidy
    - unzip
    - python-mysqldb
    - git
    - memcached
    - atsar
    - uptimed
    - subversion
    - ack-grep
    - mosh
    - update-manager-core
    - libapache2-mod-evasive