---
- name: check scripts
  template:
    src="sqmail/service/{{ item }}.j2"
    dest="{{ glx_sqmail_dir }}/bin/{{ item }}"
    owner="root"
    group="{{ glx_sqmail_groups.sqmail.gname }}"
    mode=0755
  with_items:
    - "run_pop3d"
    - "run_pop3sd"
    - "run_qmqpd"
    - "run_qmtpd"
    - "run_qmtpsd"
    - "run_send"
    - "run_smtpd"
    - "run_smtpsd"
    - "run_smtpsub"

- name: check service qmail-pop3d service
  template:
    src="sqmail/service/qmail-pop3d.service.j2"
    dest="/lib/systemd/system/qmail-pop3d.service"
    backup=no
  register: qmail_pop3d_service

- name: check service qmail-pop3sd service
  template:
    src="sqmail/service/qmail-pop3sd.service.j2"
    dest="/lib/systemd/system/qmail-pop3sd.service"
    backup=no
  register: qmail_pop3sd_service

- name: check service qmail-qmqpd service
  template:
    src="sqmail/service/qmail-qmqpd.service.j2"
    dest="/lib/systemd/system/qmail-qmqpd.service"
    backup=no
  register: qmail_qmqpd_service

- name: check service qmail-qmtpd service
  template:
    src="sqmail/service/qmail-qmtpd.service.j2"
    dest="/lib/systemd/system/qmail-qmtpd.service"
    backup=no
  register: qmail_qmtpd_service

- name: check service qmail-qmtpsd service
  template:
    src="sqmail/service/qmail-qmtpsd.service.j2"
    dest="/lib/systemd/system/qmail-qmtpsd.service"
    backup=no
  register: qmail_qmtpsd_service

- name: check service qmail-send service
  template:
    src="sqmail/service/qmail-send.service.j2"
    dest="/lib/systemd/system/qmail-send.service"
    backup=no
  register: qmail_send_service

- name: check service qmail-smtpd service
  template:
    src="sqmail/service/qmail-smtpd.service.j2"
    dest="/lib/systemd/system/qmail-smtpd.service"
    backup=no
  register: qmail_smtpd_service

- name: check service qmail-smtpsd service
  template:
    src="sqmail/service/qmail-smtpsd.service.j2"
    dest="/lib/systemd/system/qmail-smtpsd.service"
    backup=no
  register: qmail_smtpsd_service

- name: check service qmail-smtpsub service
  template:
    src="sqmail/service/qmail-smtpsub.service.j2"
    dest="/lib/systemd/system/qmail-smtpsub.service"
    backup=no
  register: qmail_smtpsub_service

- name: check rsyslog setting
  template:
    src="etc/rsyslog.d/20-sqmail.conf.j2"
    dest="/etc/rsyslog.d/20-sqmail.conf"
    backup=no
  register: rsyslog_sqmail_status

- name: regen unit files
  shell: systemctl daemon-reload
  notify:
    - restart qmail-send service
  when: qmail_send_service|changed

- name: restart rsyslog service
  service:
    name=rsyslog
    state=restarted
  when: rsyslog_sqmail_status|changed

- name: check logrotate /etc/logrotate.d/sqmail file
  template:
    src="etc/logrotate.d/sqmail.j2"
    dest="/etc/logrotate.d/sqmail"
    backup=no

### Clean for migration
- name: test {{ glx_service_dir }}/{{ glx_sqmail_service_delivery.identifier }}
  stat:
    path="{{ glx_service_dir }}/{{ glx_sqmail_service_delivery.identifier }}"
  register: send
  when: glx_sqmail_service_delivery.enable

- name: svc -dt {{ glx_service_dir }}/{{ glx_sqmail_service_delivery.identifier }} {{ glx_service_dir }}/{{ glx_sqmail_service_delivery.identifier }}/log
  shell: svc -dt {{ glx_service_dir }}/{{ glx_sqmail_service_delivery.identifier }} {{ glx_service_dir }}/{{ glx_sqmail_service_delivery.identifier }}/log
  when: glx_sqmail_service_delivery.enable and send.stat.exists

- name: remove {{ glx_sqmail_service_delivery.identifier }} files and directory
  file:
    path="{{ item }}"
    state=absent
  with_items:
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_delivery.identifier }}/log"
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_delivery.identifier }}"
    - "{{ glx_supervise_dir }}/{{ glx_sqmail_service_delivery.identifier }}"
    - "{{ glx_multilog_dir}}/{{ glx_sqmail_service_delivery.identifier }}"
  when: glx_sqmail_service_delivery.enable and send.stat.exists


### Service Systemd
### Enable services
- name: enable qmail-{{ glx_sqmail_service_delivery.name }}
  service:
    name="qmail-send"
    state=started
    enabled=yes
  when: glx_sqmail_service_delivery.enable

- name: enable qmail-{{ glx_sqmail_service_smtp.name }}
  service:
    name="qmail-smtpd"
    state=started
    enabled=yes
  when: glx_sqmail_service_smtp.enable

- name: enable qmail-{{ glx_sqmail_service_smtps.name }}
  service:
    name="qmail-smtpsd"
    state=started
    enabled=yes
  when: glx_sqmail_service_smtps.enable

- name: enable qmail-{{ glx_sqmail_service_submission.name }}
  service:
    name="qmail-smtpsub"
    state=started
    enabled=yes
  when: glx_sqmail_service_submission.enable

- name: enable qmail-{{ glx_sqmail_service_pop3.name }}
  service:
    name="qmail-pop3d"
    state=started
    enabled=yes
  when: glx_sqmail_service_pop3.enable

- name: enable qmail-{{ glx_sqmail_service_pop3s.name }}
  service:
    name="qmail-pop3sd"
    state=started
    enabled=yes
  when: glx_sqmail_service_pop3s.enable

- name: enable qmail-{{ glx_sqmail_service_qmqp.name }}
  service:
    name="qmail-qmqpd"
    state=started
    enabled=yes
  when: glx_sqmail_service_qmqp.enable

- name: enable qmail-{{ glx_sqmail_service_qmtp.name }}
  service:
    name="qmail-qmtpd"
    state=started
    enabled=yes
  when: glx_sqmail_service_qmtp.enable

- name: enable qmail-{{ glx_sqmail_service_qmtps.name }}
  service:
    name="qmail-qmtpsd"
    state=started
    enabled=yes
  when: glx_sqmail_service_qmtps.enable

### Disable services
- name: disable qmail-{{ glx_sqmail_service_delivery.name }}
  service:
    name="qmail-send"
    state=stopped
    enabled=no
  when: not glx_sqmail_service_delivery.enable

- name: disable qmail-{{ glx_sqmail_service_smtp.name }}
  service:
    name="qmail-smtpd"
    state=stopped
    enabled=no
  when: not glx_sqmail_service_smtp.enable

- name: disable qmail-{{ glx_sqmail_service_smtps.name }}
  service:
    name="qmail-smtpsd"
    state=stopped
    enabled=no
  when: not glx_sqmail_service_smtps.enable

- name: disable qmail-{{ glx_sqmail_service_submission.name }}
  service:
    name="qmail-smtpsub"
    state=stopped
    enabled=no
  when: not glx_sqmail_service_submission.enable

- name: disable qmail-{{ glx_sqmail_service_pop3.name }}
  service:
    name="qmail-pop3d"
    state=stopped
    enabled=no
  when: not glx_sqmail_service_pop3.enable

- name: disable qmail-{{ glx_sqmail_service_pop3s.name }}
  service:
    name="qmail-pop3sd"
    state=stopped
    enabled=no
  when: not glx_sqmail_service_pop3s.enable

- name: disable qmail-{{ glx_sqmail_service_qmqp.name }}
  service:
    name="qmail-qmqpd"
    state=stopped
    enabled=no
  when: not glx_sqmail_service_qmqp.enable

- name: disable qmail-{{ glx_sqmail_service_qmtp.name }}
  service:
    name="qmail-qmtpd"
    state=stopped
    enabled=no
  when: not glx_sqmail_service_qmtp.enable

- name: disable qmail-{{ glx_sqmail_service_qmtps.name }}
  service:
    name="qmail-qmtpsd"
    state=stopped
    enabled=no
  when: not glx_sqmail_service_qmtps.enable
