### Disable services
- name: disable qmail-{{ glx_sqmail_service_delivery.name }}
  service:
    name="qmail-send"
    state=stopped
    enabled=no

- name: disable qmail-{{ glx_sqmail_service_smtp.name }}
  service:
    name="qmail-smtpd"
    state=stopped
    enabled=no

- name: disable qmail-{{ glx_sqmail_service_smtps.name }}
  service:
    name="qmail-smtpsd"
    state=stopped
    enabled=no

- name: disable qmail-{{ glx_sqmail_service_submission.name }}
  service:
    name="qmail-smtpsub"
    state=stopped
    enabled=no

- name: disable qmail-{{ glx_sqmail_service_pop3.name }}
  service:
    name="qmail-pop3d"
    state=stopped
    enabled=no

- name: disable qmail-{{ glx_sqmail_service_pop3s.name }}
  service:
    name="qmail-pop3sd"
    state=stopped
    enabled=no

- name: disable qmail-{{ glx_sqmail_service_qmqp.name }}
  service:
    name="qmail-qmqpd"
    state=stopped
    enabled=no

- name: disable qmail-{{ glx_sqmail_service_qmtp.name }}
  service:
    name="qmail-qmtpd"
    state=stopped
    enabled=no

- name: disable qmail-{{ glx_sqmail_service_qmtps.name }}
  service:
    name="qmail-qmtpsd"
    state=stopped
    enabled=no
