---
ansible_port: 22

glx_ndjbdns_source_dir: "/usr/src/ndjbdns"
glx_ndjbdns_prefix: "/usr/local"
glx_ndjbdns_sysconfdir: "/etc"

glx_tinydns_root_directory: "{{ glx_ndjbdns_sysconfdir }}/ndjbdns"
glx_tinydns_zones_directory: "{{ glx_tinydns_root_directory }}/zones"
glx_tinydns_primary_directory: "{{ glx_tinydns_zones_directory }}/primary.d"
glx_tinydns_secondary_directory: "{{ glx_tinydns_zones_directory }}/secondary.d"


glx_domain_list:
  - { name: "galaxie.ici",   priv_key_name: "id_rsa", primary: "192.168.1.1", secondary: [] }