---
- name: "Clean up previous Galaxie power Save"
  file:
    path={{ item }}
    state=absent
    recurse=no
  with_items:
    - "{{ galaxie.scripts.directory }}/power_save.sh"
    - "/etc/cron.d/galaxie_power_save"

- name: "Copy powertop.service.j2 to {{ systemd_service_file_path }}/"
  template:
    src: "{{ ansible_distribution }}/{{ ansible_distribution_major_version }}/powertop.service.j2"
    dest: "{{ systemd_service_file_path }}/powertop.service"
    backup: no
  register: powertop_service


- name: "Reload systemd manager configuration"
  shell: systemctl daemon-reload
  when: powertop_service|changed

- name: "Enable powertop service"
  service:
    name: "powertop"
    state: started
    enabled: yes