---
### Configure apt-cacher-ng
- name: Install packages apt-cacher-ng ed
  apt:
    name="{{item}}"
    state=present
  with_items:
    - apt-cacher-ng
    - ed

- name: Create {{ galaxie_apt_cacher_ng_cache_dir }} directory
  file:
    path={{ galaxie_apt_cacher_ng_cache_dir }}
    owner={{ galaxie_apt_cacher_ng_user }}
    group={{ galaxie_apt_cacher_ng_group }}
    state=directory
    mode=0755

- name: Write /etc/apt-cacher-ng/acng.conf
  template:
    src=acng.conf.j2
    dest=/etc/apt-cacher-ng/acng.conf
    backup=yes
  notify:
    - restart apt-cacher-ng

### Configure Apt
- name: Write /etc/apt/apt.conf
  template:
    src=apt.conf.j2
    dest=/etc/apt/apt.conf
    backup=yes
  when: inventory_hostname in groups["apt-cacher-ng-server"]
  register: apt_config

- name: Update apt cache
  apt:
    update_cache=yes
  when: apt_config|changed

- name: Activate service
  service:
    name=apt-cacher-ng
    state=started
    enabled=yes