---
- name: "Add backports repository from {{ glx_backports_repository_url }}"
  apt_repository:
    repo: "deb {{ glx_backports_repository_url }} {{ ansible_lsb.codename }}-backports main"
    state: present
    update_cache: yes


- name: "Install OpenJDK 8"
  apt:
    name: "{{ item }}"
    state: latest
    default_release: "{{ ansible_lsb.codename }}-backports"
    update_cache: yes
  with_items:
    - "openjdk-8-jre"
    - "openjdk-8-jdk-headless"

# conf-ld -- loader options to be adjusted (for i386; AMD64 normalydefault)
- name: Check DEB_BUILD_ARCH
  shell: dpkg-architecture 2>&1 | grep '^DEB_BUILD_ARCH=' | cut -d'=' -f2
  register: DEB_BUILD_ARCH
  changed_when: false

- name: Check for last version
  script: get_basename_by_url.sh 'https://app.filebot.net/download.php?type=deb&arch={{ DEB_BUILD_ARCH.stdout }}'
  register: glx_filebot_filename
  failed_when: not glx_filebot_filename.stdout
  changed_when: False

# - debug: msg="{{ glx_filebot_filename.stdout_lines[0] }}"

- name: "portable | download installer"
  get_url:
    url: "https://app.filebot.net/download.php?type=deb&arch={{ DEB_BUILD_ARCH.stdout }}"
    dest: "/usr/src/{{ glx_filebot_filename.stdout_lines[0] }}"
