---
- include: Debian/8/install-java.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

- include: Debian/7/install-java.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "7"