---
- name: Check directorys
  file:
    path="{{item}}"
    owner=root
    group=root
    state=directory
    mode=0755
  with_items:
    - "{{ glx_packages_dir }}"
    - "{{ glx_opt_dir }}"
    - "{{ glx_src_dir }}"

- include: config-apt.yml
  tags: config, config-apt

- include: install-java.yml
  tags: install, install-java

- include: install-packages.yml
  tags: install, install-packages
